-- bullmq-outbox — Postgres schema.
-- Run once, before the app starts. Safe to re-run.
--
-- Pair it with examples/postgres-store.ts.

create table if not exists bullmq_outbox (
  -- The entry id generated by the package (a UUID by default).
  id          text primary key,

  queue_name  text        not null,
  job_name    text        not null,

  -- The job payload. The package snapshots it through JSON before it gets
  -- here, so it is always valid JSON.
  data        jsonb       not null,

  -- Job options (attempts, jobId, delay...). Null when the caller passed none.
  opts        jsonb,

  created_at  timestamptz not null,
  attempts    int         not null default 0,
  last_error  text,

  -- 'pending'   waiting to be replayed
  -- 'processed' back in Redis
  -- 'expired'   gave up after maxAttempts; kept so a human can look at it
  status      text        not null default 'pending'
                constraint bullmq_outbox_status
                check (status in ('pending', 'processed', 'expired'))
);

-- The drain's query, and the only one that touches more than a single row.
--
-- The WHERE clause is what makes it cheap. A plain index on
-- (status, created_at) works too, but it indexes every row you ever stored;
-- the partial one indexes only what is still pending. Measured on a table
-- with 500,000 processed rows and 50 pending:
--
--   partial index (this one)           16 kB
--   plain index on (status, created_at) 19 MB
--
-- Same query speed — Postgres reads 3 pages either way — but one grows with
-- your backlog and the other grows forever. With both present the planner
-- picks this one.
--
-- With no index at all the query becomes a sequential scan: 13.7 ms instead
-- of 0.9 ms on that table, degrading with every job you process.
--
-- The other three queries the store runs (save, markProcessed, markFailed)
-- are all by `id`, so the primary key already covers them. These two indexes
-- are all you need.
create index if not exists bullmq_outbox_pending
  on bullmq_outbox (created_at)
  where status = 'pending';

-- Optional: reclaim space from resolved rows. Postgres has no TTL, so this is
-- a cron job, not a setting. Only ever delete resolved rows — never 'pending'.
--
--   delete from bullmq_outbox
--    where status in ('processed', 'expired')
--      and created_at < now() - interval '7 days';
