-- bullmq-outbox — Postgres schema.
-- Run once, before the app starts. Safe to re-run.
--
-- Pair it with examples/postgres-store.ts.

create table if not exists bullmq_outbox (
  -- The entry id generated by the package (a UUID by default).
  id          text primary key,

  queue_name  text        not null,
  job_name    text        not null,

  -- The job payload. The package snapshots it through JSON before it gets
  -- here, so it is always valid JSON.
  data        jsonb       not null,

  -- Job options (attempts, jobId, delay...). Null when the caller passed none.
  opts        jsonb,

  created_at  timestamptz not null,
  attempts    int         not null default 0,
  last_error  text,

  -- 'pending'   waiting to be replayed
  -- 'processed' back in Redis
  -- 'expired'   gave up after maxAttempts; kept so a human can look at it
  status      text        not null default 'pending'
                constraint bullmq_outbox_status
                check (status in ('pending', 'processed', 'expired'))
);

-- The only query on the hot path: oldest pending first.
--
-- The WHERE clause is the important part. After an incident this table is
-- almost entirely 'processed' rows, and a partial index stays proportional to
-- what is still pending instead of to everything you ever stored. Measured at
-- 500k resolved rows: 0.83 ms to read 50 pending, with a 16 kB index on a
-- 74 MB table.
--
-- Drop the WHERE and the drain stays fast but the index grows forever. Drop
-- the index entirely and you get a sequential scan — an outbox that gets
-- slower every month, precisely when you need it.
create index if not exists bullmq_outbox_pending
  on bullmq_outbox (created_at)
  where status = 'pending';

-- Optional: reclaim space from resolved rows. Postgres has no TTL, so this is
-- a cron job, not a setting. Only ever delete resolved rows — never 'pending'.
--
--   delete from bullmq_outbox
--    where status in ('processed', 'expired')
--      and created_at < now() - interval '7 days';
