/**
 * The smallest slice of a BullMQ queue this package touches.
 *
 * Nothing here imports `bullmq`. A `Queue` from bullmq v5, v6 or
 * `@taskforcesh/bullmq-pro` all satisfy this shape structurally, so the same
 * build works across versions — and across majors that do not exist yet.
 */
export type MinimalQueue = {
  name: string;
  add(name: string, data: unknown, opts?: unknown): Promise<unknown>;
  addBulk(
    jobs: { name: string; data: unknown; opts?: unknown }[],
  ): Promise<unknown>;
};

/** A job that could not reach Redis, as handed to your store. */
export type OutboxEntry = {
  /** Stable id generated by this package. Use it as the primary key. */
  id: string;
  queueName: string;
  jobName: string;
  /**
   * The job payload, snapshotted through JSON at capture time — so it is safe
   * to persist as-is, and a later mutation of the caller's object cannot
   * change what gets replayed.
   */
  data: unknown;
  /** The job options the caller passed, minus anything unserializable. */
  opts?: unknown;
  /** ISO 8601. */
  createdAt: string;
  /** How many re-enqueue attempts have already failed. */
  attempts: number;
  /** The Redis error that sent this job to the outbox. */
  lastError?: string;
};

/**
 * Your storage, as four functions. Write them against whatever you already
 * run — Postgres, Redis, DynamoDB, Mongo, a file. See `examples/`.
 *
 * The only hard requirement is that `loadPending` never returns an entry that
 * a previous `markProcessed` accepted.
 */
export type OutboxStore = {
  /** Persist a job that failed to enqueue. Throwing here is the last resort — it is logged via `onSaveFailed` and swallowed. */
  save(entry: OutboxEntry): Promise<void>;
  /** Oldest-first entries still awaiting re-enqueue, at most `limit`. */
  loadPending(limit: number): Promise<OutboxEntry[]>;
  /** The job made it back into Redis. Delete it, or mark it done. */
  markProcessed(id: string): Promise<void>;
  /**
   * The re-enqueue failed again.
   *
   * An options object rather than positional arguments: `expired` next to
   * `attempts` would be a boolean trap, and new fields can be added later
   * without breaking every store people have written.
   */
  markFailed(failure: {
    id: string;
    /** Why the replay failed this time. */
    error: string;
    /** The new attempt count, already incremented. */
    attempts: number;
    /**
     * The entry hit `maxAttempts` and will never be retried. Move it to a
     * dead letter table or keep it for inspection — but do not let
     * `loadPending` return it again.
     */
    expired: boolean;
  }): Promise<void>;
};

/** Fired when a job could not reach Redis and was written to the store. */
export type JobSavedEvent = {
  queueName: string;
  jobName: string;
  id: string;
  error: string;
};

/** Fired when a stored job made it back into Redis. */
export type JobRequeuedEvent = {
  queueName: string;
  jobName: string;
  id: string;
  /** Milliseconds between the original failure and the successful re-enqueue. */
  ageMs: number;
  attempts: number;
};

/** Fired when a job hit `maxAttempts` and will not be retried. */
export type JobExpiredEvent = {
  queueName: string;
  jobName: string;
  id: string;
  attempts: number;
  lastError: string;
};

/** Fired when the store itself failed — the fallback's fallback. */
export type SaveFailedEvent = {
  queueName: string;
  jobName: string;
  /** The Redis error that triggered the save. */
  originalError: string;
  /** The error your store threw. */
  storeError: string;
};

/** Fired once per `flush()`. */
export type FlushEvent = {
  requeued: number;
  failed: number;
  skipped: number;
  expired: number;
};

/**
 * Optional observability. Nothing is required; hook up New Relic, Datadog,
 * OpenTelemetry, pino or nothing at all. Hooks are called fire-and-forget and
 * their exceptions are swallowed — a broken metric never breaks a job.
 */
export type OutboxHooks = {
  onJobSaved?(event: JobSavedEvent): void;
  onJobRequeued?(event: JobRequeuedEvent): void;
  onJobExpired?(event: JobExpiredEvent): void;
  onSaveFailed?(event: SaveFailedEvent): void;
  onFlush?(event: FlushEvent): void;
};

export type OutboxOptions = {
  store: OutboxStore;
  /**
   * How many times a stored job is re-enqueued before it is marked expired.
   * Default 10.
   */
  maxAttempts?: number;
  /**
   * Return false to let a failure propagate without being stored. Use it for
   * real-time queues where a job replayed minutes later is worse than a job
   * dropped — a live chat turn, a websocket push.
   */
  shouldCapture?(context: {
    queueName: string;
    jobName: string;
    /** Whatever the queue rejected with. Not guaranteed to be an `Error`. */
    error: unknown;
  }): boolean;
  /**
   * Generate entry ids. Defaults to `randomUUID()`.
   *
   * Must be unique: stores key on it, and a collision drops a job.
   */
  generateId?(): string;
} & OutboxHooks;

/** What one `flush()` did. */
export type FlushResult = {
  requeued: number;
  failed: number;
  /** Entries whose queue was not registered in this process. */
  skipped: number;
  expired: number;
  details: {
    id: string;
    queueName: string;
    jobName: string;
    status: 'requeued' | 'failed' | 'expired' | 'skipped';
    error?: string;
  }[];
};

/**
 * A BullMQ queue constructor, as NestJS calls it: `new QueueClass(name, opts)`.
 *
 * Structural, like everything else here — `Queue` from bullmq and `QueuePro`
 * from BullMQ Pro both satisfy it.
 */
export type QueueConstructor<Q extends MinimalQueue = MinimalQueue> = new (
  name: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ...args: any[]
) => Q;
